### ISSUE TITLE
Make it async 

### ISSUE THREAD

**Issue by tgermain** [devopsfaith/krakend-usage#1]
Hi,

We recently had an issue due to the reporting API being unreachable for some time. The symptom was that the krakend containers were slow to start sometime. 
We run them on kubernetes with health check and even the relatively small timeout of 5s is enough to make enough healthcheck failed and put the pod in a crashloopbackoff state.

I think this could be avoid by making the call to the external API async. That way it would avoid delaying the rest of the startup if that call take some time (or timeout).

**Comment by kpacha** [comment]
the reporter client is already started in a goroutine (https://github.com/devopsfaith/krakend-ce/blob/master/executor.go#L285-L295), so the initial handshake and all the reports are concurrent to the main process trying to start the gateway.

what other modules are you using?

**Comment by tgermain** [comment]
I was using [krakend-cd](https://github.com/devopsfaith/krakend-ce) in version `v1.1.1`.

More specifically, I configured the following module in my configuration:
- krakend-opencensus
- krakend-gologging
- a custom backend-client plugin

The issue occurs on startup, before any requests (even healthcheck requests) have hit the krakend instance.

**Comment by alombarte** [comment]
Can't reproduce
